# Generated by Django 2.1.3 on 2018-11-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.Grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.Materia')),
            ],
        ),
    ]
